/*
 * File: app/model/modelReview.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.modelReview', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.Date'
    ],

    fields: [
        {
            type: 'int',
            name: 'ORDERNUM'
        },
        {
            type: 'int',
            name: 'QTY'
        },
        {
            type: 'int',
            name: 'SCANCNT'
        },
        {
            type: 'date',
            name: 'LASTSCAN'
        }
    ]
});