/*
 * File: app/model/modelRgn.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.modelRgn', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Number'
    ],

    fields: [
        {
            type: 'int',
            name: 'IVBLTO'
        },
        {
            type: 'string',
            name: 'CMCNA1'
        },
        {
            type: 'int',
            name: 'IVPRI'
        },
        {
            type: 'int',
            name: 'IVPRICOL'
        },
        {
            type: 'float',
            name: 'GRP_CR_AMT'
        },
        {
            type: 'int',
            name: 'GRP_CR_CNT'
        },
        {
            type: 'float',
            name: 'GRP_0_AMT'
        },
        {
            type: 'int',
            name: 'GRP_0_CNT'
        },
        {
            type: 'float',
            name: 'GRP_1_AMT'
        },
        {
            type: 'int',
            name: 'GRP_1_CNT'
        },
        {
            type: 'float',
            name: 'GRP_2_AMT'
        },
        {
            type: 'int',
            name: 'GRP_2_CNT'
        },
        {
            type: 'float',
            name: 'GRP_3_AMT'
        },
        {
            type: 'int',
            name: 'GRP_3_CNT'
        },
        {
            type: 'float',
            name: 'GRP_4_AMT'
        },
        {
            type: 'int',
            name: 'GRP_4_CNT'
        },
        {
            type: 'float',
            name: 'GRP_5_AMT'
        },
        {
            type: 'int',
            name: 'GRP_5_CNT'
        },
        {
            type: 'float',
            calculate: function(data) {

                return (data.GRP_CR_AMT + data.GRP_0_AMT + data.GRP_1_AMT + data.GRP_2_AMT + data.GRP_3_AMT+ data.GRP_4_AMT + data.GRP_5_AMT);
            },
            name: 'CTOT'
        }
    ]
});