/*
 * File: app/store/store_Defaults.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.store_Defaults', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.modelDefaults',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            statefulFilters: true,
            storeId: 'store_Defaults',
            autoLoad: true,
            autoSync: true,
            model: 'MyApp.model.modelDefaults',
            proxy: {
                type: 'ajax',
                url: '/Gemini/AR/getAr_Defaults.php?DB=GI',
                reader: {
                    type: 'json',
                    rootProperty: 'root'
                }
            }
        }, cfg)]);
    }
});