/*
 * File: app/view/Win1.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Win1', {
    extend: 'Ext.window.Window',
    alias: 'widget.win1',

    requires: [
        'MyApp.view.Win1ViewModel',
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.field.Checkbox',
        'Ext.form.field.Date'
    ],

    viewModel: {
        type: 'win1'
    },
    height: 461,
    id: 'win1',
    width: 431,
    layout: 'fit',
    closeAction: 'hide',
    title: 'My Window',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            id: 'formProp',
            bodyPadding: 10,
            defaultButton: '',
            url: '/Gemini/AR/SetDefault.php?DB=GI',
            items: [
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    fieldLabel: 'Label',
                    name: 'USR'
                },
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    fieldLabel: 'Label',
                    name: 'TAG'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Description',
                    name: 'TAGD',
                    listeners: {
                        blur: 'onTextfieldBlur'
                    }
                },
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    fieldLabel: 'Label',
                    name: 'TAGACTIVE'
                },
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    fieldLabel: 'Label',
                    name: 'TAGTYPE'
                },
                {
                    xtype: 'checkboxfield',
                    anchor: '100%',
                    fieldLabel: 'Label',
                    boxLabel: 'Box Label',
                    uncheckedValue: 'N'
                },
                {
                    xtype: 'datefield',
                    anchor: '100%',
                    fieldLabel: 'Label',
                    submitFormat: 'Y-m-d'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: 'MyButton',
                            listeners: {
                                click: 'onButtonClick'
                            }
                        }
                    ]
                }
            ]
        }
    ],

    onTextfieldBlur: function(component, event, eOpts) {
        console.log('Field Changed');
    },

    onButtonClick: function(button, e, eOpts) {
        form = Ext.getCmp('formProp').getForm();
        form.submit();
    }

});