/*
 * File: app/view/Win2ViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Win2ViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.win2',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Memory'
    ],

    stores: {
        modelDefaults: {
            model: 'MyApp.model.modelDefaults',
            data: [
                {
                    USR: 'nostrum',
                    TAG: 'occaecati',
                    TAGD: 'error',
                    TAGV: 'in',
                    TAGACTIVE: false
                },
                {
                    USR: 'omnis',
                    TAG: 'vitae',
                    TAGD: 'corporis',
                    TAGV: 'minima',
                    TAGACTIVE: false
                },
                {
                    USR: 'alias',
                    TAG: 'sapiente',
                    TAGD: 'beatae',
                    TAGV: 'placeat',
                    TAGACTIVE: false
                },
                {
                    USR: 'consequatur',
                    TAG: 'et',
                    TAGD: 'ea',
                    TAGV: 'rem',
                    TAGACTIVE: false
                },
                {
                    USR: 'consectetur',
                    TAG: 'qui',
                    TAGD: 'numquam',
                    TAGV: 'voluptatem',
                    TAGACTIVE: true
                },
                {
                    USR: 'quia',
                    TAG: 'blanditiis',
                    TAGD: 'soluta',
                    TAGV: 'nemo',
                    TAGACTIVE: false
                },
                {
                    USR: 'nesciunt',
                    TAG: 'molestiae',
                    TAGD: 'fuga',
                    TAGV: 'nemo',
                    TAGACTIVE: false
                },
                {
                    USR: 'error',
                    TAG: 'ab',
                    TAGD: 'facilis',
                    TAGV: 'maiores',
                    TAGACTIVE: true
                },
                {
                    USR: 'corporis',
                    TAG: 'et',
                    TAGD: 'vero',
                    TAGV: 'in',
                    TAGACTIVE: false
                },
                {
                    USR: 'qui',
                    TAG: 'rerum',
                    TAGD: 'iusto',
                    TAGV: 'suscipit',
                    TAGACTIVE: false
                },
                {
                    USR: 'tempore',
                    TAG: 'accusantium',
                    TAGD: 'aliquam',
                    TAGV: 'et',
                    TAGACTIVE: true
                },
                {
                    USR: 'quo',
                    TAG: 'iste',
                    TAGD: 'error',
                    TAGV: 'ab',
                    TAGACTIVE: false
                },
                {
                    USR: 'laudantium',
                    TAG: 'neque',
                    TAGD: 'ut',
                    TAGV: 'voluptas',
                    TAGACTIVE: false
                },
                {
                    USR: 'officiis',
                    TAG: 'quo',
                    TAGD: 'eligendi',
                    TAGV: 'qui',
                    TAGACTIVE: false
                },
                {
                    USR: 'ut',
                    TAG: 'minus',
                    TAGD: 'nihil',
                    TAGV: 'autem',
                    TAGACTIVE: true
                },
                {
                    USR: 'et',
                    TAG: 'repellendus',
                    TAGD: 'vitae',
                    TAGV: 'et',
                    TAGACTIVE: false
                },
                {
                    USR: 'rem',
                    TAG: 'magni',
                    TAGD: 'odio',
                    TAGV: 'eum',
                    TAGACTIVE: true
                },
                {
                    USR: 'ut',
                    TAG: 'ab',
                    TAGD: 'nihil',
                    TAGV: 'temporibus',
                    TAGACTIVE: false
                },
                {
                    USR: 'autem',
                    TAG: 'excepturi',
                    TAGD: 'qui',
                    TAGV: 'reiciendis',
                    TAGACTIVE: false
                },
                {
                    USR: 'commodi',
                    TAG: 'error',
                    TAGD: 'doloribus',
                    TAGV: 'minima',
                    TAGACTIVE: true
                },
                {
                    USR: 'rem',
                    TAG: 'rerum',
                    TAGD: 'et',
                    TAGV: 'voluptatem',
                    TAGACTIVE: true
                },
                {
                    USR: 'molestiae',
                    TAG: 'enim',
                    TAGD: 'velit',
                    TAGV: 'earum',
                    TAGACTIVE: false
                },
                {
                    USR: 'sapiente',
                    TAG: 'id',
                    TAGD: 'iusto',
                    TAGV: 'molestias',
                    TAGACTIVE: true
                },
                {
                    USR: 'sint',
                    TAG: 'incidunt',
                    TAGD: 'dolore',
                    TAGV: 'voluptas',
                    TAGACTIVE: true
                },
                {
                    USR: 'sed',
                    TAG: 'quas',
                    TAGD: 'quam',
                    TAGV: 'cupiditate',
                    TAGACTIVE: true
                },
                {
                    USR: 'est',
                    TAG: 'temporibus',
                    TAGD: 'magni',
                    TAGV: 'et',
                    TAGACTIVE: true
                },
                {
                    USR: 'aut',
                    TAG: 'officiis',
                    TAGD: 'eligendi',
                    TAGV: 'non',
                    TAGACTIVE: true
                },
                {
                    USR: 'quasi',
                    TAG: 'qui',
                    TAGD: 'inventore',
                    TAGV: 'suscipit',
                    TAGACTIVE: false
                },
                {
                    USR: 'iusto',
                    TAG: 'mollitia',
                    TAGD: 'quae',
                    TAGV: 'nihil',
                    TAGACTIVE: false
                },
                {
                    USR: 'magni',
                    TAG: 'atque',
                    TAGD: 'quae',
                    TAGV: 'nemo',
                    TAGACTIVE: false
                }
            ],
            proxy: {
                type: 'memory'
            }
        }
    }

});