/*
 * File: app/view/WinBuild.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.WinBuild', {
    extend: 'Ext.window.Window',
    alias: 'widget.winbuild',

    requires: [
        'MyApp.view.WinBuildViewModel',
        'Ext.form.field.Display'
    ],

    viewModel: {
        type: 'winbuild'
    },
    height: 73,
    id: 'winbuild',
    width: 302,
    layout: 'fit',
    title: 'Message',

    items: [
        {
            xtype: 'displayfield',
            value: 'Re-Building your Aging View '
        }
    ]

});