/*
 * File: app/view/WinRegion.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.WinRegion', {
    extend: 'Ext.window.Window',
    alias: 'widget.winRegion',

    requires: [
        'MyApp.view.WinRegionViewModel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.grid.filters.filter.Number',
        'Ext.grid.filters.filter.String',
        'Ext.grid.filters.filter.List',
        'Ext.grid.filters.Filters'
    ],

    viewModel: {
        type: 'winregion'
    },
    height: 747,
    id: 'winRegion',
    width: 1354,
    layout: 'fit',
    title: 'My Window',

    items: [
        {
            xtype: 'gridpanel',
            store: 'storecbyr',
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 69,
                    dataIndex: 'IVBLTO',
                    text: 'Customer',
                    filter: {
                        type: 'number'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    width: 192,
                    dataIndex: 'CMCNA1',
                    text: 'Name',
                    filter: {
                        type: 'string'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    width: 50,
                    dataIndex: 'IVPRI',
                    text: 'AR<br>Pri',
                    filter: {
                        type: 'list'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    align: 'center',
                    text: 'Credits',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'GRP_CR_AMT',
                            text: 'Amount',
                            filter: {
                                type: 'number'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 40,
                            dataIndex: 'GRP_CR_CNT',
                            text: '#'
                        }
                    ]
                },
                {
                    xtype: 'gridcolumn',
                    align: 'center',
                    text: 'Current',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'GRP_0_AMT',
                            text: 'Amount',
                            filter: {
                                type: 'number'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 40,
                            dataIndex: 'GRP_0_CNT',
                            text: '#',
                            filter: {
                                type: 'number'
                            }
                        }
                    ]
                },
                {
                    xtype: 'gridcolumn',
                    align: 'center',
                    text: '1-15',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'GRP_1_AMT',
                            text: 'Amount',
                            filter: {
                                type: 'number'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 40,
                            dataIndex: 'GRP_1_CNT',
                            text: '#',
                            filter: {
                                type: 'number'
                            }
                        }
                    ]
                },
                {
                    xtype: 'gridcolumn',
                    align: 'center',
                    text: '16-30',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'GRP_2_AMT',
                            text: 'Amount',
                            filter: {
                                type: 'number'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 40,
                            dataIndex: 'GRP_2_CNT',
                            text: '#',
                            filter: {
                                type: 'number'
                            }
                        }
                    ]
                },
                {
                    xtype: 'gridcolumn',
                    align: 'center',
                    text: '31-60',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'GRP_3_AMT',
                            text: 'Amount',
                            filter: {
                                type: 'number'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 40,
                            dataIndex: 'GRP_3_CNT',
                            text: '#',
                            filter: {
                                type: 'number'
                            }
                        }
                    ]
                },
                {
                    xtype: 'gridcolumn',
                    align: 'center',
                    text: '61-90',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'GRP_4_AMT',
                            text: 'Amount',
                            filter: {
                                type: 'number'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 40,
                            dataIndex: 'GRP_4_CNT',
                            text: '#',
                            filter: {
                                type: 'number'
                            }
                        }
                    ]
                },
                {
                    xtype: 'gridcolumn',
                    align: 'center',
                    text: 'Over 90',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'GRP_5_AMT',
                            text: 'Amount',
                            filter: {
                                type: 'number'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 40,
                            dataIndex: 'GRP_5_CNT',
                            text: '#',
                            filter: {
                                type: 'number'
                            }
                        }
                    ]
                }
            ],
            plugins: [
                {
                    ptype: 'gridfilters'
                }
            ]
        }
    ]

});