/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'MyApp.view.MyViewportViewModel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.feature.Summary',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    viewModel: {
        type: 'myviewport'
    },
    height: 250,
    width: 400,
    layout: 'fit',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'gridpanel',
            stateful: true,
            stateId: 'C100',
            id: 'grid1',
            title: 'My Grid Panel',
            columnLines: true,
            bind: {
                store: 'storeRgn'
            },
            viewConfig: {
                loadingText: 'Retreiving Invoices for selected customer'
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    stateEvents: 'c101',
                    stateful: true,
                    text: 'Bill To',
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            stateful: true,
                            stateId: 'c102',
                            style: '{color: #3194AF;  font-weight: bold;}',
                            dataIndex: 'IVBLTO',
                            text: '#',
                            tooltip: 'Double click to display customer',
                            format: '00'
                        },
                        {
                            xtype: 'gridcolumn',
                            stateEvents: 'c103',
                            stateful: true,
                            width: 136,
                            dataIndex: 'CMCNA1',
                            text: 'Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            stateful: true,
                            stateId: 'c104',
                            hidden: true,
                            width: 187,
                            dataIndex: 'CMADDR',
                            text: 'Address'
                        },
                        {
                            xtype: 'gridcolumn',
                            stateEvents: 'c105',
                            stateful: true,
                            hidden: true,
                            dataIndex: 'CMCTRM',
                            text: 'Terms'
                        },
                        {
                            xtype: 'gridcolumn',
                            stateEvents: 'c106',
                            stateful: true,
                            hidden: true,
                            dataIndex: 'CMCNA2',
                            text: 'Address 1'
                        },
                        {
                            xtype: 'gridcolumn',
                            stateEvents: 'c107',
                            stateful: true,
                            hidden: true,
                            dataIndex: 'CMCNA3',
                            text: 'Address 2'
                        },
                        {
                            xtype: 'gridcolumn',
                            stateEvents: 'c108',
                            stateful: true,
                            hidden: true,
                            dataIndex: 'CMCNA4',
                            text: 'Address 3'
                        },
                        {
                            xtype: 'gridcolumn',
                            stateEvents: 'c109',
                            stateful: true,
                            hidden: true,
                            dataIndex: 'CMCCTY',
                            text: 'City'
                        },
                        {
                            xtype: 'gridcolumn',
                            stateEvents: 'c10',
                            stateful: true,
                            hidden: true,
                            dataIndex: 'CMST',
                            text: 'State'
                        },
                        {
                            xtype: 'gridcolumn',
                            stateEvents: 'c11',
                            stateful: true,
                            hidden: true,
                            dataIndex: 'CMZIP',
                            text: 'Zip'
                        },
                        {
                            xtype: 'gridcolumn',
                            stateEvents: 'c12',
                            stateful: true,
                            hidden: true,
                            dataIndex: 'CMCRGN',
                            text: 'Region'
                        }
                    ]
                },
                {
                    xtype: 'numbercolumn',
                    summaryType: 'count',
                    stateful: true,
                    stateId: 'c320',
                    style: '{color: #3194AF;  font-weight: bold;}',
                    dataIndex: 'IVAIV',
                    text: 'Invoice',
                    tooltip: 'Double click to display Invoice',
                    format: '00'
                },
                {
                    xtype: 'datecolumn',
                    stateful: true,
                    stateId: 'c321',
                    dataIndex: 'IVIVDT',
                    text: 'Invoice<br>Date',
                    format: 'm/j/Y'
                },
                {
                    xtype: 'numbercolumn',
                    summaryType: 'sum',
                    stateful: true,
                    stateId: 'c322',
                    align: 'end',
                    dataIndex: 'IVIVAM',
                    text: 'Invoice <br>Amount'
                },
                {
                    xtype: 'numbercolumn',
                    summaryType: 'sum',
                    stateful: true,
                    stateId: 'c323',
                    align: 'end',
                    dataIndex: 'IVNPOS',
                    text: 'Net<br>Posted'
                },
                {
                    xtype: 'numbercolumn',
                    summaryType: 'sum',
                    stateful: true,
                    stateId: 'c324',
                    width: 90,
                    align: 'end',
                    dataIndex: 'INVDUE',
                    text: 'Due'
                },
                {
                    xtype: 'numbercolumn',
                    stateful: true,
                    stateId: 'c325',
                    width: 77,
                    align: 'end',
                    dataIndex: 'DAYSPD',
                    text: 'Days<br>Past<br>Due',
                    format: '00'
                },
                {
                    xtype: 'numbercolumn',
                    stateful: true,
                    stateId: 'c326',
                    width: 48,
                    align: 'center',
                    dataIndex: 'AGE_GRP',
                    text: 'Age<br>Grp',
                    format: '00'
                },
                {
                    xtype: 'numbercolumn',
                    stateful: true,
                    stateId: 'c327',
                    hidden: true,
                    dataIndex: 'IVSEQ',
                    text: 'Seq#',
                    format: '00'
                },
                {
                    xtype: 'gridcolumn',
                    stateEvents: 'c328',
                    stateful: true,
                    width: 54,
                    align: 'center',
                    dataIndex: 'IVTRMS',
                    text: 'Terms<br>Code'
                },
                {
                    xtype: 'gridcolumn',
                    stateEvents: 'c400',
                    stateful: true,
                    hidden: true,
                    text: 'Ship To',
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            stateful: true,
                            stateId: 'c401',
                            dataIndex: 'IVCUST',
                            text: '#',
                            format: '00'
                        },
                        {
                            xtype: 'gridcolumn',
                            stateEvents: 'c402',
                            stateful: true,
                            dataIndex: 'SHPNA1',
                            text: 'Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            stateEvents: 'c406',
                            stateful: true,
                            dataIndex: 'SHPADR',
                            text: 'Address'
                        },
                        {
                            xtype: 'gridcolumn',
                            stateEvents: 'c404',
                            stateful: true,
                            hidden: true,
                            dataIndex: 'SHPNA2',
                            text: 'Address 1'
                        },
                        {
                            xtype: 'gridcolumn',
                            stateEvents: 'c405',
                            stateful: true,
                            hidden: true,
                            dataIndex: 'SHPNA3',
                            text: 'Address 2'
                        },
                        {
                            xtype: 'gridcolumn',
                            stateEvents: 'c406',
                            stateful: true,
                            hidden: true,
                            dataIndex: 'SHPNA4',
                            text: 'Address 3'
                        },
                        {
                            xtype: 'gridcolumn',
                            stateEvents: 'c407',
                            stateful: true,
                            hidden: true,
                            dataIndex: 'SHPCTY',
                            text: 'City'
                        },
                        {
                            xtype: 'gridcolumn',
                            stateEvents: 'c408',
                            stateful: true,
                            hidden: true,
                            dataIndex: 'SHPST',
                            text: 'State'
                        },
                        {
                            xtype: 'gridcolumn',
                            stateEvents: 'c409',
                            stateful: true,
                            hidden: true,
                            dataIndex: 'SHPZIP',
                            text: 'Zip'
                        }
                    ]
                },
                {
                    xtype: 'gridcolumn',
                    stateEvents: 'c500',
                    stateful: true,
                    text: 'Event Review',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            stateEvents: 'c501',
                            stateful: true,
                            width: 49,
                            dataIndex: 'EVCONT',
                            text: '#'
                        },
                        {
                            xtype: 'gridcolumn',
                            stateEvents: 'c502',
                            stateful: true,
                            style: '{color: #3194AF;  font-weight: bold;}',
                            width: 600,
                            dataIndex: 'EVDESC',
                            text: 'Events',
                            tooltip: 'Double click to link to events page'
                        }
                    ]
                }
            ],
            listeners: {
                celldblclick: 'onGrid1CellDblClick'
            },
            features: [
                {
                    ftype: 'summary',
                    dock: 'top'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            hidden: true,
                            text: 'Export',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'to Excel',
                                        listeners: {
                                            click: 'onMenuitemClick'
                                        }
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'to CSV',
                                        listeners: {
                                            click: 'onMenuitemClick1'
                                        }
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'to HTML',
                                        listeners: {
                                            click: 'onMenuitemClick2'
                                        }
                                    }
                                ]
                            }
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onViewportAfterRender'
    },

    onGrid1CellDblClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        var col =tableview.eventPosition.column.dataIndex;
        var cust = record.data.IVBLTO;
        var name = record.data.CMCNA1;
        var inv = record.data.IVAIV;
        var ivd = record.data.IVD;

        if (col == 'IVBLTO'){
            url = "http://192.168.100.80:1965/harris-CGI/CustomerSelect.d2w/REPORT?baseVar=BaseConfigurationGI%2Eicl&portal=CUSTOMER&customerNumber=" + cust + "&customerName=" + name;
            window.open(url,'_blank');

        }
        if (col == 'IVAIV'){
            url = "http://192.168.100.80:1965/harris-CGI/SelectInvoice.d2w/DISPLAY?baseVar=BaseConfigurationGI%2Eicl&portal=CUSTOMER&customerNumber=" + cust + "&customerName=" + name + "&invoiceNumber=" + inv +"&invoiceDate=" + ivd + "&formatToPrint=Y";
            window.open(url,'_blank');
        }
        if (col == 'EVDESC'){

            url = "http://192.168.100.80:1965/harris-CGI/CustomerContactEvent.d2w/REPORT?baseVar=BaseConfigurationGI%2Eicl&portal=CUSTOMER&customerNumber=" + cust + "&customerName="+ name + "&inclOpen=Y&inclComp=&inclOverDue=";
             window.open(url,'_blank');
        }

    },

    onMenuitemClick: function(item, e, eOpts) {
        var params = Ext.urlDecode(location.search.substring(1));
        console.log('Params: ', params);

                var grid = Ext.getCmp('grid1');
                var dt = Ext.Date.format(new Date(), 'Y-m-d h:i:s');
                grid.saveDocumentAs({
                    type: 'xlsx',
                    title: 'AR Aging for Customer ' + params.NAME + ' and Group '  + params.GRP,
                    fileName: 'ARAging_By_Customer_' + params.NAME + '-' + params.GRP + '_' + dt +'.xlsx'


        });
    },

    onMenuitemClick1: function(item, e, eOpts) {
         var params = Ext.urlDecode(location.search.substring(1));
                console.log('Params: ', params);
        var grid = Ext.getCmp('grid1');
        var dt = Ext.Date.format(new Date(), 'Y-m-d h:i:s');
        grid.saveDocumentAs({
            type: 'csv',
            title: 'AR Aging for Customer ' + params.NAME + ' and Group '  + params.GRP,
            fileName: 'ARAging_By_Customer_' + params.NAME + '-' + params.GRP + '_' + dt +'.csv'
        });
    },

    onMenuitemClick2: function(item, e, eOpts) {
         var params = Ext.urlDecode(location.search.substring(1));
        var grid = Ext.getCmp('grid1');
        var dt = Ext.Date.format(new Date(), 'Y-m-d h:i:s');
        grid.saveDocumentAs({
            type: 'html',
            title: 'AR Aging for Customer ' + params.NAME + ' and Group '  + params.GRP,
            fileName: 'ARAging_By_Customer_' + params.NAME + '-' + params.GRP + '_' + dt + '.html'
        });
    },

    onViewportAfterRender: function(component, eOpts) {
        var params = Ext.urlDecode(location.search.substring(1));
        console.log(params);

        Ext.getCmp('grid1').setTitle('Invoice for Customer ' + params.NAME);
    }

});