/*
 * File: app/view/MyViewportViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewportViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.myviewport',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Memory'
    ],

    stores: {
        modelMs: {
            model: 'MyApp.model.modelM',
            data: [
                {
                    ORDERNUM: 463,
                    CMPSEQ: 920,
                    COMPONENT: 'ab',
                    CMPID: 'ab',
                    QTY: 402.87,
                    UOM: 'aut',
                    SEQSTATUS: 'unde',
                    CMPNOTES: 'et'
                },
                {
                    ORDERNUM: 848,
                    CMPSEQ: 353,
                    COMPONENT: 'voluptatibus',
                    CMPID: 'labore',
                    QTY: 160.65,
                    UOM: 'mollitia',
                    SEQSTATUS: 'sit',
                    CMPNOTES: 'labore'
                },
                {
                    ORDERNUM: 501,
                    CMPSEQ: 964,
                    COMPONENT: 'possimus',
                    CMPID: 'quaerat',
                    QTY: 455.76,
                    UOM: 'voluptatem',
                    SEQSTATUS: 'adipisci',
                    CMPNOTES: 'sapiente'
                },
                {
                    ORDERNUM: 175,
                    CMPSEQ: 850,
                    COMPONENT: 'minus',
                    CMPID: 'repellat',
                    QTY: 268.69,
                    UOM: 'autem',
                    SEQSTATUS: 'cumque',
                    CMPNOTES: 'odit'
                },
                {
                    ORDERNUM: 549,
                    CMPSEQ: 11,
                    COMPONENT: 'labore',
                    CMPID: 'dolorem',
                    QTY: 735.81,
                    UOM: 'quis',
                    SEQSTATUS: 'quisquam',
                    CMPNOTES: 'suscipit'
                },
                {
                    ORDERNUM: 781,
                    CMPSEQ: 873,
                    COMPONENT: 'cumque',
                    CMPID: 'voluptas',
                    QTY: 844.82,
                    UOM: 'dignissimos',
                    SEQSTATUS: 'et',
                    CMPNOTES: 'nobis'
                },
                {
                    ORDERNUM: 812,
                    CMPSEQ: 6,
                    COMPONENT: 'ex',
                    CMPID: 'sunt',
                    QTY: 508.69,
                    UOM: 'consequatur',
                    SEQSTATUS: 'fuga',
                    CMPNOTES: 'labore'
                },
                {
                    ORDERNUM: 373,
                    CMPSEQ: 937,
                    COMPONENT: 'laboriosam',
                    CMPID: 'ipsum',
                    QTY: 399.55,
                    UOM: 'et',
                    SEQSTATUS: 'iste',
                    CMPNOTES: 'eius'
                },
                {
                    ORDERNUM: 911,
                    CMPSEQ: 605,
                    COMPONENT: 'et',
                    CMPID: 'sequi',
                    QTY: 738.51,
                    UOM: 'dolores',
                    SEQSTATUS: 'debitis',
                    CMPNOTES: 'iure'
                },
                {
                    ORDERNUM: 515,
                    CMPSEQ: 723,
                    COMPONENT: 'voluptatem',
                    CMPID: 'assumenda',
                    QTY: 981.05,
                    UOM: 'dolor',
                    SEQSTATUS: 'minus',
                    CMPNOTES: 'sequi'
                },
                {
                    ORDERNUM: 506,
                    CMPSEQ: 777,
                    COMPONENT: 'consequuntur',
                    CMPID: 'tenetur',
                    QTY: 341.95,
                    UOM: 'iusto',
                    SEQSTATUS: 'doloremque',
                    CMPNOTES: 'explicabo'
                },
                {
                    ORDERNUM: 791,
                    CMPSEQ: 104,
                    COMPONENT: 'amet',
                    CMPID: 'laboriosam',
                    QTY: 589.52,
                    UOM: 'aut',
                    SEQSTATUS: 'ut',
                    CMPNOTES: 'enim'
                },
                {
                    ORDERNUM: 329,
                    CMPSEQ: 172,
                    COMPONENT: 'earum',
                    CMPID: 'quidem',
                    QTY: 326.66,
                    UOM: 'consequatur',
                    SEQSTATUS: 'sit',
                    CMPNOTES: 'voluptates'
                },
                {
                    ORDERNUM: 647,
                    CMPSEQ: 867,
                    COMPONENT: 'esse',
                    CMPID: 'temporibus',
                    QTY: 456.84,
                    UOM: 'vero',
                    SEQSTATUS: 'non',
                    CMPNOTES: 'iure'
                },
                {
                    ORDERNUM: 208,
                    CMPSEQ: 168,
                    COMPONENT: 'iusto',
                    CMPID: 'voluptatem',
                    QTY: 363.42,
                    UOM: 'iste',
                    SEQSTATUS: 'nesciunt',
                    CMPNOTES: 'alias'
                },
                {
                    ORDERNUM: 228,
                    CMPSEQ: 564,
                    COMPONENT: 'aperiam',
                    CMPID: 'aliquid',
                    QTY: 466.77,
                    UOM: 'exercitationem',
                    SEQSTATUS: 'illo',
                    CMPNOTES: 'quibusdam'
                },
                {
                    ORDERNUM: 815,
                    CMPSEQ: 303,
                    COMPONENT: 'alias',
                    CMPID: 'ea',
                    QTY: 552.61,
                    UOM: 'omnis',
                    SEQSTATUS: 'fugit',
                    CMPNOTES: 'voluptatibus'
                },
                {
                    ORDERNUM: 448,
                    CMPSEQ: 809,
                    COMPONENT: 'molestiae',
                    CMPID: 'magni',
                    QTY: 374.89,
                    UOM: 'veritatis',
                    SEQSTATUS: 'dolorem',
                    CMPNOTES: 'voluptatibus'
                },
                {
                    ORDERNUM: 542,
                    CMPSEQ: 533,
                    COMPONENT: 'quibusdam',
                    CMPID: 'laboriosam',
                    QTY: 718.75,
                    UOM: 'dolore',
                    SEQSTATUS: 'cupiditate',
                    CMPNOTES: 'sapiente'
                },
                {
                    ORDERNUM: 745,
                    CMPSEQ: 34,
                    COMPONENT: 'voluptas',
                    CMPID: 'deleniti',
                    QTY: 223.49,
                    UOM: 'ad',
                    SEQSTATUS: 'in',
                    CMPNOTES: 'occaecati'
                },
                {
                    ORDERNUM: 396,
                    CMPSEQ: 973,
                    COMPONENT: 'reiciendis',
                    CMPID: 'illum',
                    QTY: 613.06,
                    UOM: 'occaecati',
                    SEQSTATUS: 'quidem',
                    CMPNOTES: 'voluptas'
                },
                {
                    ORDERNUM: 368,
                    CMPSEQ: 347,
                    COMPONENT: 'natus',
                    CMPID: 'autem',
                    QTY: 125.7,
                    UOM: 'exercitationem',
                    SEQSTATUS: 'blanditiis',
                    CMPNOTES: 'praesentium'
                },
                {
                    ORDERNUM: 590,
                    CMPSEQ: 230,
                    COMPONENT: 'facere',
                    CMPID: 'et',
                    QTY: 477.9,
                    UOM: 'tenetur',
                    SEQSTATUS: 'in',
                    CMPNOTES: 'consequatur'
                },
                {
                    ORDERNUM: 417,
                    CMPSEQ: 246,
                    COMPONENT: 'qui',
                    CMPID: 'excepturi',
                    QTY: 450.27,
                    UOM: 'voluptate',
                    SEQSTATUS: 'alias',
                    CMPNOTES: 'sit'
                },
                {
                    ORDERNUM: 324,
                    CMPSEQ: 909,
                    COMPONENT: 'occaecati',
                    CMPID: 'quis',
                    QTY: 363.92,
                    UOM: 'consequatur',
                    SEQSTATUS: 'id',
                    CMPNOTES: 'unde'
                },
                {
                    ORDERNUM: 149,
                    CMPSEQ: 465,
                    COMPONENT: 'illo',
                    CMPID: 'quis',
                    QTY: 984.27,
                    UOM: 'aut',
                    SEQSTATUS: 'eius',
                    CMPNOTES: 'ipsa'
                },
                {
                    ORDERNUM: 997,
                    CMPSEQ: 320,
                    COMPONENT: 'corrupti',
                    CMPID: 'dolorem',
                    QTY: 29.77,
                    UOM: 'aut',
                    SEQSTATUS: 'aut',
                    CMPNOTES: 'sunt'
                },
                {
                    ORDERNUM: 814,
                    CMPSEQ: 470,
                    COMPONENT: 'vero',
                    CMPID: 'sint',
                    QTY: 381.05,
                    UOM: 'expedita',
                    SEQSTATUS: 'quis',
                    CMPNOTES: 'reiciendis'
                },
                {
                    ORDERNUM: 73,
                    CMPSEQ: 48,
                    COMPONENT: 'saepe',
                    CMPID: 'soluta',
                    QTY: 324.8,
                    UOM: 'quia',
                    SEQSTATUS: 'dolor',
                    CMPNOTES: 'ab'
                },
                {
                    ORDERNUM: 235,
                    CMPSEQ: 164,
                    COMPONENT: 'dolorem',
                    CMPID: 'nesciunt',
                    QTY: 145.98,
                    UOM: 'consectetur',
                    SEQSTATUS: 'atque',
                    CMPNOTES: 'ad'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }
    }

});