/*
 * File: app/model/model_Rgns1.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.model_Rgns1', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'IVBLTO'
        },
        {
            name: 'CMCNA1'
        },
        {
            name: 'IVPRI'
        },
        {
            name: 'GRP_CR_AMT'
        },
        {
            name: 'GRP_CR_CNT'
        },
        {
            name: 'GRP_0_AMT'
        },
        {
            name: 'GRP_0_CNT'
        },
        {
            name: 'GRP_1_AMT'
        },
        {
            name: 'GRP_1_CNT'
        },
        {
            name: 'GRP_2_AMT'
        },
        {
            name: 'GRP_2_CNT'
        },
        {
            name: 'GRP_3_AMT'
        },
        {
            name: 'GRP_3_CNT'
        },
        {
            name: 'GRP_4_AMT'
        },
        {
            name: 'GRP_4_CNT'
        },
        {
            name: 'GRP_5_AMT'
        },
        {
            name: 'GRP_5_CNT'
        }
    ]
});